<a href="https://colab.research.google.com/github/jtista/BellaBeat-/blob/main/BellaBeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

### Daily Activity

In [2]:
#load daily activity  dataset
daily_activity = pd.read_csv('/content/dailyActivity_merged.csv')

In [3]:
print(f"Shape: {daily_activity.shape}")
print(daily_activity.head())
print(daily_activity.info())
print(daily_activity.describe())

Shape: (940, 15)
           Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0  1503960366    4/12/2016       13162           8.50             8.50
1  1503960366    4/13/2016       10735           6.97             6.97
2  1503960366    4/14/2016       10460           6.74             6.74
3  1503960366    4/15/2016        9762           6.28             6.28
4  1503960366    4/16/2016       12669           8.16             8.16

   LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                       0.0                1.88                      0.55
1                       0.0                1.57                      0.69
2                       0.0                2.44                      0.40
3                       0.0                2.14                      1.26
4                       0.0                2.71                      0.41

   LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                 6.06                      0.0                 25
1                 4.71                      0.0                 21
2                 3.91                      0.0                 30
3                 2.83                      0.0                 29
4                 5.04                      0.0                 36

   FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories
0                   13                   328               728      1985
1                   19                   217               776      1797
2                   11                   181              1218      1776
3                   34                   209               726      1745
4                   10                   221               773      1863
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        940 non-null    int64
 1   ActivityDate              940 non-null    object
 2   TotalSteps                940 non-null    int64
 3   TotalDistance             940 non-null    float64
 4   TrackerDistance           940 non-null    float64
 5   LoggedActivitiesDistance  940 non-null    float64
 6   VeryActiveDistance        940 non-null    float64
 7   ModeratelyActiveDistance  940 non-null    float64
 8   LightActiveDistance       940 non-null    float64
 9   SedentaryActiveDistance   940 non-null    float64
 10  VeryActiveMinutes         940 non-null    int64
 11  FairlyActiveMinutes       940 non-null    int64
 12  LightlyActiveMinutes      940 non-null    int64
 13  SedentaryMinutes          940 non-null    int64
 14  Calories                  940 non-null    int64
dtypes: float64(7), int64(7), object(1)
memory usage: 110.3+ KB
None
                 Id    TotalSteps  TotalDistance  TrackerDistance  \
count  9.400000e+02    940.000000     940.000000       940.000000
mean   4.855407e+09   7637.910638       5.489702         5.475351
std    2.424805e+09   5087.150742       3.924606         3.907276
min    1.503960e+09      0.000000       0.000000         0.000000
25%    2.320127e+09   3789.750000       2.620000         2.620000
50%    4.445115e+09   7405.500000       5.245000         5.245000
75%    6.962181e+09  10727.000000       7.712500         7.710000
max    8.877689e+09  36019.000000      28.030001        28.030001

       LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
count                940.000000          940.000000                940.000000
mean                   0.108171            1.502681                  0.567543
std                    0.619897            2.658941                  0.883580
min                    0.000000            0.000000                  0.000000
25%                    0.000000            0.000000                  0.000000
50%                    0.000000            0.210000                  0.240000
75%                    0.000000            2.052500                  0.800000
max                    4.942142           21.920000                  6.480000

       LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
count           940.000000               940.000000         940.000000
mean              3.340819                 0.001606          21.164894
std               2.040655                 0.007346          32.844803
min               0.000000                 0.000000           0.000000
25%               1.945000                 0.000000           0.000000
50%               3.365000                 0.000000           4.000000
75%               4.782500                 0.000000          32.000000
max              10.710000                 0.110000         210.000000

       FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  \
count           940.000000            940.000000        940.000000
mean             13.564894            192.812766        991.210638
std              19.987404            109.174700        301.267437
min               0.000000              0.000000          0.000000
25%               0.000000            127.000000        729.750000
50%               6.000000            199.000000       1057.500000
75%              19.000000            264.000000       1229.500000
max             143.000000            518.000000       1440.000000

          Calories
count   940.000000
mean   2303.609574
std     718.166862
min       0.000000
25%    1828.500000
50%    2134.000000
75%    2793.250000
max    4900.000000

### Sleep Minutes

In [4]:
#load sleep minutes dataset
sleep_minutes = pd.read_csv('/content/minuteSleep_merged.csv')

In [5]:
print(f"Shape: {sleep_minutes.shape}")
print(sleep_minutes.head())
print(sleep_minutes.info())
print(sleep_minutes.describe())

Shape: (188521, 4)
           Id                  date  value        logId
0  1503960366  4/12/2016 2:47:30 AM      3  11380564589
1  1503960366  4/12/2016 2:48:30 AM      2  11380564589
2  1503960366  4/12/2016 2:49:30 AM      1  11380564589
3  1503960366  4/12/2016 2:50:30 AM      1  11380564589
4  1503960366  4/12/2016 2:51:30 AM      1  11380564589
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188521 entries, 0 to 188520
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Id      188521 non-null  int64
 1   date    188521 non-null  object
 2   value   188521 non-null  int64
 3   logId   188521 non-null  int64
dtypes: int64(3), object(1)
memory usage: 5.8+ MB
None
                 Id          value         logId
count  1.885210e+05  188521.000000  1.885210e+05
mean   4.996595e+09       1.095793  1.149611e+10
std    2.066950e+09       0.328673  6.822863e+07
min    1.503960e+09       1.000000  1.137223e+10
25%    3.977334e+09       1.000000  1.143931e+10
50%    4.702922e+09       1.000000  1.150114e+10
75%    6.962181e+09       1.000000  1.155253e+10
max    8.792010e+09       3.000000  1.161625e+10

### Weight Log Info

In [6]:
#load weight log info
weight_log_info = pd.read_csv('/content/weightLogInfo_merged.csv')

In [7]:
print(f"Shape: {weight_log_info.shape}")
print(weight_log_info.head())
print(weight_log_info.info())
print(weight_log_info.describe())

Shape: (67, 8)
           Id                   Date    WeightKg  WeightPounds   Fat  \
0  1503960366   5/2/2016 11:59:59 PM   52.599998    115.963147  22.0
1  1503960366   5/3/2016 11:59:59 PM   52.599998    115.963147   NaN
2  1927972279   4/13/2016 1:08:52 AM  133.500000    294.317120   NaN
3  2873212765  4/21/2016 11:59:59 PM   56.700001    125.002104   NaN
4  2873212765  5/12/2016 11:59:59 PM   57.299999    126.324875   NaN

         BMI  IsManualReport          LogId
0  22.650000            True  1462233599000
1  22.650000            True  1462319999000
2  47.540001           False  1460509732000
3  21.450001            True  1461283199000
4  21.690001            True  1463097599000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              67 non-null     int64
 1   Date            67 non-null     object
 2   WeightKg        67 non-null     float64
 3   WeightPounds    67 non-null     float64
 4   Fat             2 non-null      float64
 5   BMI             67 non-null     float64
 6   IsManualReport  67 non-null     bool
 7   LogId           67 non-null     int64
dtypes: bool(1), float64(4), int64(2), object(1)
memory usage: 3.9+ KB
None
                 Id    WeightKg  WeightPounds       Fat        BMI  \
count  6.700000e+01   67.000000     67.000000   2.00000  67.000000
mean   7.009282e+09   72.035821    158.811801  23.50000  25.185224
std    1.950322e+09   13.923206     30.695415   2.12132   3.066963
min    1.503960e+09   52.599998    115.963147  22.00000  21.450001
25%    6.962181e+09   61.400002    135.363832  22.75000  23.959999
50%    6.962181e+09   62.500000    137.788914  23.50000  24.389999
75%    8.877689e+09   85.049999    187.503152  24.25000  25.559999
max    8.877689e+09  133.500000    294.317120  25.00000  47.540001

              LogId
count  6.700000e+01
mean   1.461772e+12
std    7.829948e+08
min    1.460444e+12
25%    1.461079e+12
50%    1.461802e+12
75%    1.462375e+12
max    1.463098e+12

In [8]:
#check for null values
daily_activity.isnull().sum()

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

In [9]:
sleep_minutes.isnull().sum()

Id       0
date     0
value    0
logId    0
dtype: int64

In [10]:
weight_log_info.isnull().sum()

Id                 0
Date               0
WeightKg           0
WeightPounds       0
Fat               65
BMI                0
IsManualReport     0
LogId              0
dtype: int64

In [11]:
#check for duplicates
daily_activity.duplicated().sum()

np.int64(0)

In [12]:
sleep_minutes.duplicated().sum()

np.int64(543)

In [13]:
weight_log_info.duplicated().sum()

np.int64(0)

In [14]:
#check uniques users
daily_activity['Id'].nunique()

33

In [15]:
sleep_minutes['Id'].nunique()

24

In [16]:
weight_log_info['Id'].nunique()

8

In [17]:
#Fixing dates to date time format

# Reload dataframes to ensure original date string formats for conversion
daily_activity = pd.read_csv('/content/dailyActivity_merged.csv')
sleep_minutes = pd.read_csv('/content/minuteSleep_merged.csv')
weight_log_info = pd.read_csv('/content/weightLogInfo_merged.csv')

daily_activity['ActivityDate'] = pd.to_datetime(daily_activity['ActivityDate'], format='%m/%d/%Y')
sleep_minutes['date'] = pd.to_datetime(sleep_minutes['date'], format='%m/%d/%Y %I:%M:%S %p')
weight_log_info['Date'] = pd.to_datetime(weight_log_info['Date'], format='%m/%d/%Y %I:%M:%S %p')

#organising dates from lowest to highest
print("Daily Activity date range:", daily_activity['ActivityDate'].min(), "to", daily_activity['ActivityDate'].max())
print("Sleep Minutes date range:", sleep_minutes['date'].min(), "to", sleep_minutes['date'].max())
print("Weight Log Info date range:", weight_log_info['Date'].min(), "to", weight_log_info['Date'].max())

Daily Activity date range: 2016-04-12 00:00:00 to 2016-05-12 00:00:00
Sleep Minutes date range: 2016-04-11 20:48:00 to 2016-05-12 09:56:00
Weight Log Info date range: 2016-04-12 06:47:11 to 2016-05-12 23:59:59

In [18]:
#changing the format of the dates to dd-mm-yyyy
daily_activity['ActivityDate'] = daily_activity['ActivityDate'].dt.strftime('%d-%m-%Y')
sleep_minutes['date'] = sleep_minutes['date'].dt.strftime('%d-%m-%Y')
weight_log_info['Date'] = weight_log_info['Date'].dt.strftime('%d-%m-%Y')

### Verifying dates

In [19]:
#verify
print(daily_activity['ActivityDate'].head())

0    12-04-2016
1    13-04-2016
2    14-04-2016
3    15-04-2016
4    16-04-2016
Name: ActivityDate, dtype: object

In [20]:
print(sleep_minutes['date'].head())

0    12-04-2016
1    12-04-2016
2    12-04-2016
3    12-04-2016
4    12-04-2016
Name: date, dtype: object

In [21]:
print(weight_log_info['Date'].head())

0    02-05-2016
1    03-05-2016
2    13-04-2016
3    21-04-2016
4    12-05-2016
Name: Date, dtype: object

### Process Stage

In [22]:
#standardise column names
daily_activity.columns = daily_activity.columns.str.lower().str.replace(' ', '_')
sleep_minutes.columns = sleep_minutes.columns.str.lower().str.replace(' ', '_')
weight_log_info.columns = weight_log_info.columns.str.lower().str.replace(' ', '_')
#verify
print(daily_activity.columns.tolist())
print(sleep_minutes.columns.tolist())
print(weight_log_info.columns.tolist())

['id', 'activitydate', 'totalsteps', 'totaldistance', 'trackerdistance', 'loggedactivitiesdistance', 'veryactivedistance', 'moderatelyactivedistance', 'lightactivedistance', 'sedentaryactivedistance', 'veryactiveminutes', 'fairlyactiveminutes', 'lightlyactiveminutes', 'sedentaryminutes', 'calories']
['id', 'date', 'value', 'logid']
['id', 'date', 'weightkg', 'weightpounds', 'fat', 'bmi', 'ismanualreport', 'logid']

In [24]:
daily_activity['activitydate']= pd.to_datetime(daily_activity["activitydate"], format='%d-%m-%Y')
daily_activity['day_of_week'] = daily_activity['activitydate'].dt.day_name()
daily_activity['month'] = daily_activity['activitydate'].dt.month_name()

print(daily_activity.dtypes)

id                                   int64
activitydate                datetime64[ns]
totalsteps                           int64
totaldistance                      float64
trackerdistance                    float64
loggedactivitiesdistance           float64
veryactivedistance                 float64
moderatelyactivedistance           float64
lightactivedistance                float64
sedentaryactivedistance            float64
veryactiveminutes                    int64
fairlyactiveminutes                  int64
lightlyactiveminutes                 int64
sedentaryminutes                     int64
calories                             int64
day_of_week                         object
month                               object
dtype: object

In [25]:
#weight log
weight_log_info['date']= pd.to_datetime(weight_log_info['date'], format='%d-%m-%Y')
weight_log_info['ismanualreport'] = weight_log_info['ismanualreport'].astype(bool)
print(weight_log_info.dtypes)

id                         int64
date              datetime64[ns]
weightkg                 float64
weightpounds             float64
fat                      float64
bmi                      float64
ismanualreport              bool
logid                      int64
dtype: object

In [45]:
sleep_minutes['date']=pd.to_datetime(sleep_minutes['date'], format='%d-%m-%Y')
sleep_minutes['date_only'] = sleep_minutes['date'].dt.date

print(sleep_minutes.dtypes)

id                     int64
date          datetime64[ns]
value                  int64
logid                  int64
date_opnly            object
date_only             object
dtype: object

## Handle Null values

In [28]:
print("Nulls in Daily Activity:")
print(daily_activity.isnull().sum())

print("\nNulls in Sleep Minutes:")
print(sleep_minutes.isnull().sum())

print("\nNulls in Weight Log Info:")
print(weight_log_info.isnull().sum())

Nulls in Daily Activity:
id                          0
activitydate                0
totalsteps                  0
totaldistance               0
trackerdistance             0
loggedactivitiesdistance    0
veryactivedistance          0
moderatelyactivedistance    0
lightactivedistance         0
sedentaryactivedistance     0
veryactiveminutes           0
fairlyactiveminutes         0
lightlyactiveminutes        0
sedentaryminutes            0
calories                    0
day_of_week                 0
month                       0
dtype: int64

Nulls in Sleep Minutes:
id            0
date          0
value         0
logid         0
date_opnly    0
dtype: int64

Nulls in Weight Log Info:
id                 0
date               0
weightkg           0
weightpounds       0
fat               65
bmi                0
ismanualreport     0
logid              0
dtype: int64

In [29]:
weight_log_info = weight_log_info.drop(columns=['fat'])
print("Fat column dropped. Remaining columns:", weight_log_info.columns.tolist())

Fat column dropped. Remaining columns: ['id', 'date', 'weightkg', 'weightpounds', 'bmi', 'ismanualreport', 'logid']

### Remove Duplicates

In [32]:
print("Before Daily Activity", len(daily_activity))
daily_activity = daily_activity.drop_duplicates()
print("After Daily Activity", len(daily_activity))

print("Before - Weight Log:", len(weight_log_info))
weight_log_info = weight_log_info.drop_duplicates()
print("After  - Weight Log:", len(weight_log_info))

print("Before - Minute Sleep:", len(sleep_minutes))
sleep_minutes = sleep_minutes.drop_duplicates()
print("After  - Minute Sleep:", len(sleep_minutes))

Before Daily Activity 940
After Daily Activity 940
Before - Weight Log: 67
After  - Weight Log: 67
Before - Minute Sleep: 188521
After  - Minute Sleep: 1819

### Remove illogical values

In [33]:
#daily activities where total steps are 0 removed
print("Rows with 0 steps:", (daily_activity['totalsteps'] == 0).sum())
daily_activity = daily_activity[daily_activity['totalsteps'] > 0]
print("Rows remaining after removing 0-step days:", len(daily_activity))

Rows with 0 steps: 77
Rows remaining after removing 0-step days: 863

In [34]:
#removing any negative values
numeric_cols = ['totalsteps', 'totaldistance', 'calories',
                'veryactiveminutes', 'fairlyactiveminutes',
                'lightlyactiveminutes', 'sedentaryminutes']

for col in numeric_cols:
    neg_count = (daily_activity[col] < 0).sum()
    print(f"Negative values in {col}: {neg_count}")

Negative values in totalsteps: 0
Negative values in totaldistance: 0
Negative values in calories: 0
Negative values in veryactiveminutes: 0
Negative values in fairlyactiveminutes: 0
Negative values in lightlyactiveminutes: 0
Negative values in sedentaryminutes: 0

In [37]:
print("Weight range (kg):", weight_log_info['weightkg'].min(), "to", weight_log_info['weightkg'].max())
print("BMI range:", weight_log_info['bmi'].min(), "to", weight_log_info['bmi'].max())

Weight range (kg): 52.5999984741211 to 133.5
BMI range: 21.4500007629395 to 47.5400009155273

### Aggregate Minute sleep to daily level

In [47]:
daily_sleep = sleep_minutes.groupby(['id', 'date_only']).agg(
    total_minutes_asleep = ('value', lambda x: (x == 1).sum()),  # value == 1 means asleep
    total_minutes_in_bed = ('value', 'count')                    # all minutes recorded = in bed
).reset_index()

In [48]:
daily_sleep = daily_sleep.rename(columns={'date_only': 'date'})
daily_sleep['date'] = pd.to_datetime(daily_sleep['date'])

In [49]:
print(daily_sleep.head())
print(f"Shape: {daily_sleep.shape}")

           id       date  total_minutes_asleep  total_minutes_in_bed
0  1503960366 2016-04-12                     1                     3
1  1503960366 2016-04-13                     2                     4
2  1503960366 2016-04-15                     1                     3
3  1503960366 2016-04-16                     3                     8
4  1503960366 2016-04-17                     1                     2
Shape: (449, 4)

### Merge datasets

In [50]:
#Merge daily activity with daily sleep on Id and Date
activity_sleep = pd.merge(
    daily_activity,
    daily_sleep,
    left_on  = ['id', 'activitydate'],
    right_on = ['id', 'date'],
    how = 'left'
)

# Drop the duplicate date column from sleep
activity_sleep = activity_sleep.drop(columns=['date'])

print(f"Merged dataset shape: {activity_sleep.shape}")
print(activity_sleep.head())

Merged dataset shape: (863, 19)
           id activitydate  totalsteps  totaldistance  trackerdistance  \
0  1503960366   2016-04-12       13162           8.50             8.50
1  1503960366   2016-04-13       10735           6.97             6.97
2  1503960366   2016-04-14       10460           6.74             6.74
3  1503960366   2016-04-15        9762           6.28             6.28
4  1503960366   2016-04-16       12669           8.16             8.16

   loggedactivitiesdistance  veryactivedistance  moderatelyactivedistance  \
0                       0.0                1.88                      0.55
1                       0.0                1.57                      0.69
2                       0.0                2.44                      0.40
3                       0.0                2.14                      1.26
4                       0.0                2.71                      0.41

   lightactivedistance  sedentaryactivedistance  veryactiveminutes  \
0                 6.06                      0.0                 25
1                 4.71                      0.0                 21
2                 3.91                      0.0                 30
3                 2.83                      0.0                 29
4                 5.04                      0.0                 36

   fairlyactiveminutes  lightlyactiveminutes  sedentaryminutes  calories  \
0                   13                   328               728      1985
1                   19                   217               776      1797
2                   11                   181              1218      1776
3                   34                   209               726      1745
4                   10                   221               773      1863

  day_of_week  month  total_minutes_asleep  total_minutes_in_bed
0     Tuesday  April                   1.0                   3.0
1   Wednesday  April                   2.0                   4.0
2    Thursday  April                   NaN                   NaN
3      Friday  April                   1.0                   3.0
4    Saturday  April                   3.0                   8.0

In [54]:
activity_sleep['activitydate'] = pd.to_datetime(activity_sleep['activitydate'], format='%d-%m-%Y').dt.strftime('%d-%m-%Y')
weight_log_info['date'] = weight_log_info['date'].dt.strftime('%d-%m-%Y')

In [57]:
from google.colab import drive
drive.mount('/content/drive')

import os
output_dir = '/content/drive/MyDrive/Bellabeat'
os.makedirs(output_dir, exist_ok=True)

#saved files on google drive
activity_sleep.to_csv(f'{output_dir}/cleaned_activity_sleep.csv', index=False)
weight_log_info.to_csv(f'{output_dir}/cleaned_weight_log.csv',         index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).