<a href="https://colab.research.google.com/github/jtista/BellaBeat-/blob/main/BellaBeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

### Daily Activity

In [ ]:
#load daily activity  dataset
daily_activity = pd.read_csv('/content/dailyActivity_merged.csv')

In [ ]:
print(f"Shape: {daily_activity.shape}")
print(daily_activity.head())
print(daily_activity.info())
print(daily_activity.describe())

Shape: (457, 15)
           Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0  1503960366    3/25/2016       11004           7.11             7.11
1  1503960366    3/26/2016       17609          11.55            11.55
2  1503960366    3/27/2016       12736           8.53             8.53
3  1503960366    3/28/2016       13231           8.93             8.93
4  1503960366    3/29/2016       12041           7.85             7.85

   LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                       0.0                2.57                      0.46
1                       0.0                6.92                      0.73
2                       0.0                4.66                      0.16
3                       0.0                3.19                      0.79
4                       0.0                2.16                      1.09

   LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                 4.07                      0.0                 33
1                 3.91                      0.0                 89
2                 3.71                      0.0                 56
3                 4.95                      0.0                 39
4                 4.61                      0.0                 28

   FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories
0                   12                   205               804      1819
1                   17                   274               588      2154
2                    5                   268               605      1944
3                   20                   224              1080      1932
4                   28                   243               763      1886
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        457 non-null    int64
 1   ActivityDate              457 non-null    object
 2   TotalSteps                457 non-null    int64
 3   TotalDistance             457 non-null    float64
 4   TrackerDistance           457 non-null    float64
 5   LoggedActivitiesDistance  457 non-null    float64
 6   VeryActiveDistance        457 non-null    float64
 7   ModeratelyActiveDistance  457 non-null    float64
 8   LightActiveDistance       457 non-null    float64
 9   SedentaryActiveDistance   457 non-null    float64
 10  VeryActiveMinutes         457 non-null    int64
 11  FairlyActiveMinutes       457 non-null    int64
 12  LightlyActiveMinutes      457 non-null    int64
 13  SedentaryMinutes          457 non-null    int64
 14  Calories                  457 non-null    int64
dtypes: float64(7), int64(7), object(1)
memory usage: 53.7+ KB
None
                 Id    TotalSteps  TotalDistance  TrackerDistance  \
count  4.570000e+02    457.000000     457.000000       457.000000
mean   4.628595e+09   6546.562363       4.663523         4.609847
std    2.293781e+09   5398.493064       4.082072         4.068540
min    1.503960e+09      0.000000       0.000000         0.000000
25%    2.347168e+09   1988.000000       1.410000         1.280000
50%    4.057193e+09   5986.000000       4.090000         4.090000
75%    6.391747e+09  10198.000000       7.160000         7.110000
max    8.877689e+09  28497.000000      27.530001        27.530001

       LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
count                457.000000          457.000000                457.000000
mean                   0.179427            1.180897                  0.478643
std                    0.849232            2.487159                  0.830995
min                    0.000000            0.000000                  0.000000
25%                    0.000000            0.000000                  0.000000
50%                    0.000000            0.000000                  0.020000
75%                    0.000000            1.310000                  0.670000
max                    6.727057           21.920000                  6.400000

       LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
count           457.000000               457.000000         457.000000
mean              2.890197                 0.001904          16.623632
std               2.237523                 0.008487          28.919704
min               0.000000                 0.000000           0.000000
25%               0.870000                 0.000000           0.000000
50%               2.930000                 0.000000           0.000000
75%               4.460000                 0.000000          25.000000
max              12.510000                 0.100000         202.000000

       FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  \
count           457.000000            457.000000        457.000000
mean             13.070022            170.070022        995.282276
std              36.208635            122.205372        337.021404
min               0.000000              0.000000         32.000000
25%               0.000000             64.000000        728.000000
50%               1.000000            181.000000       1057.000000
75%              16.000000            257.000000       1285.000000
max             660.000000            720.000000       1440.000000

          Calories
count   457.000000
mean   2189.452954
std     815.484523
min       0.000000
25%    1776.000000
50%    2062.000000
75%    2667.000000
max    4562.000000

### Sleep Minutes

In [ ]:
#load sleep minutes dataset
sleep_minutes = pd.read_csv('/content/minuteSleep_merged.csv')

In [ ]:
print(f"Shape: {sleep_minutes.shape}")
print(sleep_minutes.head())
print(sleep_minutes.info())
print(sleep_minutes.describe())

Shape: (198559, 4)
           Id                  date  value        logId
0  1503960366  3/13/2016 2:39:30 AM      1  11114919637
1  1503960366  3/13/2016 2:40:30 AM      1  11114919637
2  1503960366  3/13/2016 2:41:30 AM      1  11114919637
3  1503960366  3/13/2016 2:42:30 AM      1  11114919637
4  1503960366  3/13/2016 2:43:30 AM      1  11114919637
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198559 entries, 0 to 198558
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Id      198559 non-null  int64
 1   date    198559 non-null  object
 2   value   198559 non-null  int64
 3   logId   198559 non-null  int64
dtypes: int64(3), object(1)
memory usage: 6.1+ MB
None
                 Id          value         logId
count  1.985590e+05  198559.000000  1.985590e+05
mean   4.824304e+09       1.085899  1.124161e+10
std    2.173935e+09       0.314480  7.969858e+07
min    1.503960e+09       1.000000  1.110365e+10
25%    2.347168e+09       1.000000  1.116551e+10
50%    4.702922e+09       1.000000  1.124395e+10
75%    6.775889e+09       1.000000  1.131074e+10
max    8.792010e+09       3.000000  1.137488e+10

### Weight Log Info

In [ ]:
#load weight log info
weight_log_info = pd.read_csv('/content/weightLogInfo_merged.csv')

In [ ]:
print(f"Shape: {weight_log_info.shape}")
print(weight_log_info.head())
print(weight_log_info.info())
print(weight_log_info.describe())

Shape: (33, 8)
           Id                  Date    WeightKg  WeightPounds   Fat  \
0  1503960366  4/5/2016 11:59:59 PM   53.299999    117.506384  22.0
1  1927972279  4/10/2016 6:33:26 PM  129.600006    285.719105   NaN
2  2347167796  4/3/2016 11:59:59 PM   63.400002    139.773078  10.0
3  2873212765  4/6/2016 11:59:59 PM   56.700001    125.002104   NaN
4  2873212765  4/7/2016 11:59:59 PM   57.200001    126.104416   NaN

         BMI  IsManualReport          LogId
0  22.969999            True  1459900799000
1  46.169998           False  1460313206000
2  24.770000            True  1459727999000
3  21.450001            True  1459987199000
4  21.650000            True  1460073599000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              33 non-null     int64
 1   Date            33 non-null     object
 2   WeightKg        33 non-null     float64
 3   WeightPounds    33 non-null     float64
 4   Fat             2 non-null      float64
 5   BMI             33 non-null     float64
 6   IsManualReport  33 non-null     bool
 7   LogId           33 non-null     int64
dtypes: bool(1), float64(4), int64(2), object(1)
memory usage: 2.0+ KB
None
                 Id    WeightKg  WeightPounds        Fat        BMI  \
count  3.300000e+01   33.000000     33.000000   2.000000  33.000000
mean   6.477156e+09   73.442425    161.912831  16.000000  25.730909
std    2.308888e+09   16.531127     36.444897   8.485281   4.330387
min    1.503960e+09   53.299999    117.506384  10.000000  21.450001
25%    4.702922e+09   61.700001    136.025217  13.000000  24.100000
50%    6.962181e+09   62.500000    137.788914  16.000000  24.389999
75%    8.877689e+09   85.800003    189.156628  19.000000  25.760000
max    8.877689e+09  129.600006    285.719105  22.000000  46.169998

              LogId
count  3.300000e+01
mean   1.459959e+12
std    3.088072e+08
min    1.459382e+12
25%    1.459753e+12
50%    1.459987e+12
75%    1.460160e+12
max    1.460506e+12

In [ ]:
#check for null values
daily_activity.isnull().sum()

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

In [ ]:
sleep_minutes.isnull().sum()

Id       0
date     0
value    0
logId    0
dtype: int64

In [ ]:
weight_log_info.isnull().sum()

Id                 0
Date               0
WeightKg           0
WeightPounds       0
Fat               31
BMI                0
IsManualReport     0
LogId              0
dtype: int64

In [ ]:
#check for duplicates
daily_activity.duplicated().sum()

np.int64(0)

In [ ]:
sleep_minutes.duplicated().sum()

np.int64(525)

In [ ]:
weight_log_info.duplicated().sum()

np.int64(0)

In [ ]:
#check uniques users
daily_activity['Id'].nunique()

35

In [ ]:
sleep_minutes['Id'].nunique()

23

In [ ]:
weight_log_info['Id'].nunique()

11

In [ ]:
#Fixing dates to date time format

# Reload dataframes to ensure original date string formats for conversion
daily_activity = pd.read_csv('/content/dailyActivity_merged.csv')
sleep_minutes = pd.read_csv('/content/minuteSleep_merged.csv')
weight_log_info = pd.read_csv('/content/weightLogInfo_merged.csv')

daily_activity['ActivityDate'] = pd.to_datetime(daily_activity['ActivityDate'], format='%m/%d/%Y')
sleep_minutes['date'] = pd.to_datetime(sleep_minutes['date'], format='%m/%d/%Y %I:%M:%S %p')
weight_log_info['Date'] = pd.to_datetime(weight_log_info['Date'], format='%m/%d/%Y %I:%M:%S %p')

#organising dates from lowest to highest
print("Daily Activity date range:", daily_activity['ActivityDate'].min(), "to", daily_activity['ActivityDate'].max())
print("Sleep Minutes date range:", sleep_minutes['date'].min(), "to", sleep_minutes['date'].max())
print("Weight Log Info date range:", weight_log_info['Date'].min(), "to", weight_log_info['Date'].max())

Daily Activity date range: 2016-03-12 00:00:00 to 2016-04-12 00:00:00
Sleep Minutes date range: 2016-03-11 21:19:30 to 2016-04-12 08:35:00
Weight Log Info date range: 2016-03-30 23:59:59 to 2016-04-12 23:59:59

In [ ]:
#changing the format of the dates to dd-mm-yyyy
daily_activity['ActivityDate'] = daily_activity['ActivityDate'].dt.strftime('%d-%m-%Y')
sleep_minutes['date'] = sleep_minutes['date'].dt.strftime('%d-%m-%Y')
weight_log_info['Date'] = weight_log_info['Date'].dt.strftime('%d-%m-%Y')

### Verifying dates

In [ ]:
#verify
print(daily_activity['ActivityDate'].head())

0    25-03-2016
1    26-03-2016
2    27-03-2016
3    28-03-2016
4    29-03-2016
Name: ActivityDate, dtype: object

In [ ]:
print(sleep_minutes['date'].head())

0    13-03-2016
1    13-03-2016
2    13-03-2016
3    13-03-2016
4    13-03-2016
Name: date, dtype: object

In [ ]:
print(weight_log_info['Date'].head())

0    05-04-2016
1    10-04-2016
2    03-04-2016
3    06-04-2016
4    07-04-2016
Name: Date, dtype: object

### Process Stage

In [ ]:
#standardise column names
daily_activity.columns = daily_activity.columns.str.lower().str.replace(' ', '_')
sleep_minutes.columns = sleep_minutes.columns.str.lower().str.replace(' ', '_')
weight_log_info.columns = weight_log_info.columns.str.lower().str.replace(' ', '_')
#verify
print(daily_activity.columns.tolist())
print(sleep_minutes.columns.tolist())
print(weight_log_info.columns.tolist())

['id', 'activitydate', 'totalsteps', 'totaldistance', 'trackerdistance', 'loggedactivitiesdistance', 'veryactivedistance', 'moderatelyactivedistance', 'lightactivedistance', 'sedentaryactivedistance', 'veryactiveminutes', 'fairlyactiveminutes', 'lightlyactiveminutes', 'sedentaryminutes', 'calories']
['id', 'date', 'value', 'logid']
['id', 'date', 'weightkg', 'weightpounds', 'fat', 'bmi', 'ismanualreport', 'logid']

In [ ]:
#Fix data types
#Daily activity - convert date and ensure numeric columns are correct
daily_activity['activitydate']= pd.to_datetime(daily_activity["activitydate"])
daily_activity['day_of_week'] = daily_activity['activitydate'].dt.day_name()
daily_activity['month'] = daily_activity['activitydate'].dt.month_name()

print(daily_activity.dtypes)

id                                   int64
activitydate                datetime64[ns]
totalsteps                           int64
totaldistance                      float64
trackerdistance                    float64
loggedactivitiesdistance           float64
veryactivedistance                 float64
moderatelyactivedistance           float64
lightactivedistance                float64
sedentaryactivedistance            float64
veryactiveminutes                    int64
fairlyactiveminutes                  int64
lightlyactiveminutes                 int64
sedentaryminutes                     int64
calories                             int64
day_of_week                         object
month                               object
dtype: object

In [ ]:
#weight log
weight_log_info['date']= pd.to_datetime(weight_log_info['date'], format='%d-%m-%Y')
weight_log_info['ismanualreport'] = weight_log_info['ismanualreport'].astype(bool)
print(weight_log_info.dtypes)

id                         int64
date              datetime64[ns]
weightkg                 float64
weightpounds             float64
fat                      float64
bmi                      float64
ismanualreport              bool
logid                      int64
dtype: object

In [ ]:
#minutes sleep
sleep_minutes['date']=pd.to_datetime(sleep_minutes['date'])
sleep_minutes['date_opnly'] = sleep_minutes['date'].dt.date

print(sleep_minutes.dtypes)

id                     int64
date          datetime64[ns]
value                  int64
logid                  int64
date_opnly            object
dtype: object

## Handle Null values

In [ ]:
print("Nulls in Daily Activity:")
print(daily_activity.isnull().sum())

print("\nNulls in Sleep Minutes:")
print(sleep_minutes.isnull().sum())

print("\nNulls in Weight Log Info:")
print(weight_log_info.isnull().sum())

Nulls in Daily Activity:
id                          0
activitydate                0
totalsteps                  0
totaldistance               0
trackerdistance             0
loggedactivitiesdistance    0
veryactivedistance          0
moderatelyactivedistance    0
lightactivedistance         0
sedentaryactivedistance     0
veryactiveminutes           0
fairlyactiveminutes         0
lightlyactiveminutes        0
sedentaryminutes            0
calories                    0
day_of_week                 0
month                       0
dtype: int64

Nulls in Sleep Minutes:
id            0
date          0
value         0
logid         0
date_opnly    0
dtype: int64

Nulls in Weight Log Info:
id                 0
date               0
weightkg           0
weightpounds       0
fat               31
bmi                0
ismanualreport     0
logid              0
dtype: int64

In [ ]:
weight_log_info = weight_log_info.drop(columns=['fat'])
print("Fat column dropped. Remaining columns:", weight_log_info.columns.tolist())

Fat column dropped. Remaining columns: ['id', 'date', 'weightkg', 'weightpounds', 'bmi', 'ismanualreport', 'logid']

### Remove Duplicates

In [ ]:
print("Before Daily Activity", len(daily_activity))
daily_activity = daily_activity.drop_duplicates()
print("After Daily Activity", len(daily_activity))

Before Daily Activity 457
After Daily Activity 457